More of the new arg processing implementation

diff --git a/udots b/udots
--- a/udots
+++ b/udots
@@ -1,51 +1,69 @@
 #!/usr/bin/env bash
 
 VERSION="0.1.0"
-CONFIG_DIR="$HOME/.config/udots/udots-config.sh"
 UMACROS_DIR="$HOME/.local/lib/umacros"
 
-# Dependency error
-depError () {
-  [[ $? -ne 0 ]] && {
-    echo "[DEPENDENCY FAILURE] $1 does not exist"
-    exit 1
-  }
+[[ ! -f "${UMACROS_DIR:?Undefined}" ]] && {
+  echo "[DEPENDENCY FAILURE] Cannot find umacros"
+  exit 1
 }
-
 source "$UMACROS_DIR"
-depError "$UMACROS_DIR"
 
-source "$CONFIG_DIR"
-depError "$CONFIG_DIR"
 
 
 # =====================================================
 # Parse config changes
 # =====================================================
-for arg in "${allArgs[@]:0:3}"; do
+for arg in "${allArgs[@]}"; do
+
   # Slice each item from arguments into its own array
   pArg "$arg"
+
   case "${currentArg[0]}" in
-    "--adopt")
-      ADOPT=1
+    "--config"|"-c")
+      [[ ! -f "${currentArg[1]}" ]] && {
+        echo "[ERR] '${currentArg[1]}' is an invalid config file or does not exist"
+        exit 1
+      }
+
+      ARG_CONFIG_DIR="${currentArg[1]}"
       ;;
 
-    "--config"|"-c")
-      CONFIG_DIR="${currentArg[1]}"
+    "--adopt")
+      ARG_ADOPT=1
       ;;
 
     "--repo"|"-r")
-      REPO_DIR="${currentArg[1]}"
+      [[ ! -d "${currentArg[1]}" ]] && {
+        echo "[ERR] '${currentArg[1]}' is an invalid repo directory or does not exist"
+        exit 1
+      }
+
+      ARG_REPO_DIR="${currentArg[1]}"
+      ;;
+
+    "--no-color"|"-nc")
+      ARG_COLOR=0
+      ;;
+
+    *)
+      break
       ;;
   esac
 done
 
-cat <<END
-CONFIG: $CONFIG_DIR
-REPO:   $REPO_DIR
-ADOPT:  $ADOPT
-END
-exit 0
+
+
+# =====================================================
+# Modify config variables based on config arguments
+# =====================================================
+CONFIG_DIR=${ARG_CONFIG_DIR:-${CONFIG_DIR:-$HOME/.config/udots/udots-config.sh}}
+
+source "$CONFIG_DIR"
+
+ADOPT="${ARG_ADOPT:-${ADOPT:-0}}"
+REPO_DIR="${ARG_REPO_DIR:-${REPO_DIR:?Please define a repo in the config}}"
+COLOR="${ARG_COLOR:-${COLOR:-1}}"
 
 
 
@@ -57,19 +75,27 @@ printHelp () {
 Description:
   A bash wrapper for gnu stow to manage dotfiles.
 
-Usage: udots [CONFIG] [OPTION]
+Usage: udots [CONFIG] [OPERATION]
 
-CONFIG:
+CONFIG: 
+These options MUST be passed before operations and you can pass multiple options
+
+  -c, --config [CONFIG PATH]
+    Use a custom config file
+  
+  -r, --repo [REPO PATH]
+    Use a custom repo directory
+
   --adopt
     Use stow with --adopt
   
-  -c, --config
-    Use a custom config file
+  -nc, --no-color
+    Disable colored output
 
-  -r, --repo
-    Use a custom repo
 
-OPTIONS:
+OPERATIONS: 
+Pick a SINGLE option from these and it MUST be passed after config options
+
   -i, --install [PKGNAME]
     Install [PKGNAME]
 
@@ -103,22 +129,17 @@ fi
 
 
 
-
 # =====================================================
-# Functions
+# Error and Colored Messages
 # =====================================================
 paintMsg () {
-  [[ $COLOR -eq 0 ]] && {
-    echo "${3}${4}"
-    return
-  }
-
+  [[ ${COLOR} -eq 0 ]] && { echo "${3}${4}" && return ;}
   paint "$1" "$2" "$3" "$4"
 }
 
 listItems () { 
   echo -e "\nAvailable packages:"
-  [[ $COLOR -eq 0 ]] && lscolor="never"
+  [[ ${COLOR} -eq 0 ]] && lscolor="never"
   ls -1 -d "$REPO/"*/ --color="${lscolor:-always}" |\
     sed "s|$REPO/||g; s|/||g" |\
     nl -w3 -s " "
@@ -143,6 +164,12 @@ err () {
   [[ "$1" =~ ^(noPkg|noPkgExist)$ ]] && listItems
   [[ ! "$1" =~ ^(noTargetExist|invalid)$ ]] && exit 1
 }
+
+
+
+# =====================================================
+# Functions
+# =====================================================
 
 stowLink () {
   stow -d "$REPO" -t "$HOME" "$1" ${@:2}
@@ -175,25 +202,8 @@ stowDelink () {
 # =====================================================
 
 for arg in "${allArgs[@]}"; do
-  # Slice each item into its own array
-  IFS=$'\n' read -d "" -ra currentArg <<< "${arg// /$'\n'}"
-  case "$1" in
-    # ======================================
-    # Parse config changes
-    # ======================================
-    "--adopt")
-      stowAdopt=1
-      ;;
-
-    "--config"|"-c")
-      CONFIG_DIR="$1"
-      ;;
-    Use a custom config file
-
-    "--repo"|"-r")
-      REPO_DIR="$1"
-      ;;
-
+  pArg "$arg"
+  case "${currentArg[0]}" in
     "--add"|"-a")
       pkgName="$2"
       [[ -z "$pkgName" ]] && { err noAddPkg ; }
@@ -299,9 +309,9 @@ for arg in "${allArgs[@]}"; do
       ;;
 
     -*) 
-      err invalid
-      echo ""
       printHelp
+      echo ""
+      err invalid "$1"
       ;;
 
     *)
